[general]
board = "nano-new"
# After flashing, open the serial console at 57600 baud.
open-console = true
serial-baudrate = 57600
# Install avrdude
# Install avr-gcc
# cargo install ravedude
# ls /dev/ttyUSB* /dev/ttyACM*
# sudo chmod a+rw /dev/ttyUSB0
port = "/dev/tty.usbserial-2110"

# For documentation about this file, check here:
# https://github.com/Rahix/avr-hal/blob/main/ravedude/README.md#ravedudetoml-format
