[package]
name = "sensors"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal = {version = "1.0",optional = true}
ufmt = { version = "0.2.0", optional = true }
